spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assembly
    username: postgres
    password: root

  flyway:
    baseline-description: << Schema Dev Flyway >>

  activemq:
    broker-url: tcp://emu.rmq.cloudamqp.com:1883
    password: jL3We0sYLQf7LPud_Sf_KPDaZQNK71nM
    user: ydcbylod:ydcbylod

  jms:
    listener:
      acknowledge-mode: auto

queue:
  name: queue

management:
  health:
    jms:
      enabled: false