spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/assembly
    username: postgres
    password: root
  flyway:
    baseline-description: << Schema Dev Flyway >>

  activemq:
    broker-url: amqp://ydcbylod:jL3We0sYLQf7LPud_Sf_KPDaZQNK71nM@emu.rmq.cloudamqp.com/ydcbylod
    password: fec5f706-b06c-4d41-a49d-16d8a99051d9
    non-blocking-redelivery: true


  jms:
    listener:
      auto-startup: false
      acknowledge-mode: auto

topic: asssembly
management:
  health:
    jms:
      enabled: false