spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: assembly
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      base-path: "/api"